### ISSUE TITLE
swap: avoid security vulnerability in apache commons-collections

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/swap#23]
See  https://github.com/sul-dlss/openwayback/compare/d46e1996fa0908c864c5a985c4f9a52a16f2777c...master

- also send info upstream to openwayback

**Comment by cbeer** [comment]
👍 to getting them to fix it upstream.

**Comment by ndushay** [comment]
filed PR iipc/webarchive-commons#77 to get it fixed upstream ... (and created issue https://github.com/iipc/webarchive-commons/issues/76)
